name: ButtonCore
main: buttondevteam.core.MainPlugin
version: 1.0
author: TBMCPlugins
commands:
  updateplugin:
    description: Update a TBMC plugin
  schrestart:
    description: Schedules a restart for a given time.
  primerestart:
    description: Restarts the server as soon as nobody is online.
